In [1]:
import pandas as pd
import os
import re

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 1862)

## Get year from file name

In [2]:
def get_numbers_from_filename(filename):
    return re.search(r'\d+', filename).group(0)

## Add year as column

df["year"] = get_numbers_from_filename(filename)

## 1992

In [3]:
df_1992 = pd.read_excel('KHV_1992.xls', dtype='object')

In [4]:
df_1992.sample()

,LAND,REGBEZ,KREIS,GEMEINDE,NAME1,NAME2,NAME3,NAME4,STRASSE,PLZ,ORT,TELEFON,TRAEGER,NAMET1,NAMET2,NAMET3,NAMET4,ART,BETTEN_P,BETTEN_I,AUGEN_P,AUGEN_I,CHIR_P,CHIR_I,C_GEF_P,C_GEF_I,C_KIN_P,C_KIN_I,C_PLA_P,C_PLA_I,C_THOR_P,C_THOR_I,C_UNF_P,C_UNF_I,FRAUEN_P,FRAUEN_I,F_FRAU_P,F_FRAU_I,F_GEBURT,F_GEBUR0,HNO_P,HNO_I,HUG_P,HUG_I,INNERE_P,INNERE_I,I_ENDO_P,I_ENDO_I,I_GAST_P,I_GAST_I,I_HAEM_P,I_HAEM_I,I_KARD_P,I_KARD_I,I_LUB_P,I_LUB_I,I_NEPH_P,I_NEPH_I,I_RHEUM_,I_RHEUM1,I_GER_P,I_GER_I,KINDER_P,KINDER_I,KJPSYCH_,KJPSYCH2,MKG_P,MKG_I,NEURCH_P,NEURCH_I,NEUROL_P,NEUROL_I,NUKLEAR_,NUKLEAR3,ORTH_P,ORTH_I,O_RHEU_P,O_RHEU_I,PSYCH_P,PSYCH_I,P_SUCHT_,P_SUCHT4,PSYSOM_P,PSYSOM_I,STRAHL_P,STRAHL_I,UROL_P,UROL_I,SONST_P,SONST_I,TN_GER,TN_KJPSY,TN_PSYCH,TN_PSYSO,TN_SONST,TN_SUM
2042,12,0,17,280,Diakonissenmutterhaus Luise-,Henrietten-Stift Krankenhaus,NaN,NaN,Klosterkirchplatz 1-19,14797,Lehnin,(03382)-431,2,Evangelisches Diakonissenhaus,Berlin-Teltow,NaN,NaN,2,160,152,0,0,57,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,72,72,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
df_1992.columns

Index(['LAND', 'REGBEZ', 'KREIS', 'GEMEINDE', 'NAME1', 'NAME2', 'NAME3',
       'NAME4', 'STRASSE', 'PLZ', 'ORT', 'TELEFON', 'TRAEGER', 'NAMET1',
       'NAMET2', 'NAMET3', 'NAMET4', 'ART', 'BETTEN_P', 'BETTEN_I', 'AUGEN_P',
       'AUGEN_I', 'CHIR_P', 'CHIR_I', 'C_GEF_P', 'C_GEF_I', 'C_KIN_P',
       'C_KIN_I', 'C_PLA_P', 'C_PLA_I', 'C_THOR_P', 'C_THOR_I', 'C_UNF_P',
       'C_UNF_I', 'FRAUEN_P', 'FRAUEN_I', 'F_FRAU_P', 'F_FRAU_I', 'F_GEBURT',
       'F_GEBUR0', 'HNO_P', 'HNO_I', 'HUG_P', 'HUG_I', 'INNERE_P', 'INNERE_I',
       'I_ENDO_P', 'I_ENDO_I', 'I_GAST_P', 'I_GAST_I', 'I_HAEM_P', 'I_HAEM_I',
       'I_KARD_P', 'I_KARD_I', 'I_LUB_P', 'I_LUB_I', 'I_NEPH_P', 'I_NEPH_I',
       'I_RHEUM_', 'I_RHEUM1', 'I_GER_P', 'I_GER_I', 'KINDER_P', 'KINDER_I',
       'KJPSYCH_', 'KJPSYCH2', 'MKG_P', 'MKG_I', 'NEURCH_P', 'NEURCH_I',
       'NEUROL_P', 'NEUROL_I', 'NUKLEAR_', 'NUKLEAR3', 'ORTH_P', 'ORTH_I',
       'O_RHEU_P', 'O_RHEU_I', 'PSYCH_P', 'PSYCH_I', 'P_SUCHT_', 'P_SUCHT4',
       'PSYSOM_P', 'PSYSOM_I', 'STRAHL_P', 'STRAHL_I', 'UROL_P', 'UROL_I',
       'SONST_P', 'SONST_I', 'TN_GER', 'TN_KJPSY', 'TN_PSYCH', 'TN_PSYSO',
       'TN_SONST', 'TN_SUM'],
      dtype='object')

In [6]:
# TODO: Prüfen: Steht BETTEN_I für Betten insgesamt?
df_1992 = df_1992.rename(columns={'LAND': 'Land', 'KREIS': 'Kreis', 'GEMEINDE': 'Gemeinde', 'NAME1': 'Name1', 'ORT': 'Ort', 'TRAEGER': 'Traeger', 'NAMET1': 'T_Name1', 'ART':'Art', 'BETTEN_I': 'Betten_Ins'})

In [7]:
df_1992 = df_1992[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

In [8]:
df_1992["year"] = get_numbers_from_filename("KHV_1992.xls")

In [9]:
df_1992.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,year
1159,07,37,005,Kreiskrankenhaus,Bad Bergzabern,1,Landkreis Sdliche Weinstraáe,2,175,1992

## 1995

In [10]:
df_1995 = pd.read_excel('KHV_1995.XLS', 'KH', dtype='object')

In [11]:
# TODO: Prüfen: Steht BETTEN_I für Betten insgesamt?
df_1995 = df_1995.rename(columns={'LAND': 'Land', 'KREIS': 'Kreis', 'GEMEINDE': 'Gemeinde', 'NAME1': 'Name1', 'ORT': 'Ort', 'TRAEGER': 'Traeger', 'NAMET1': 'T_Name1', 'ART':'Art', 'BETTEN_I': 'Betten_Ins'})

In [12]:
df_1995 = df_1995[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

In [13]:
df_1995.dtypes

Land          object
Kreis         object
Gemeinde      object
Name1         object
Ort           object
Traeger       object
T_Name1       object
Art           object
Betten_Ins    object
dtype: object

In [14]:
df_1995 = df_1995[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

In [15]:
df_1995["year"] = get_numbers_from_filename("KHV_1995.XLS")

In [16]:
df_1995.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,year
1011,06,35,003,Stadtkrankenhaus,Bad Wildungen,1,Magistrat der Stadt,2,197,1995

## 2003 - 2005

In [17]:
filenames = [
 'KHV_2003.xls',
 'KHV_2004.xls',
 'KHV_2005.xls',]

In [18]:
# df_from_each_file = (pd.read_excel(file, 'KHV', dtype='object') for file in filenames)
df_from_each_file = []

for file in filenames:
    data = pd.read_excel(file, sheet_name=4, dtype='object')
    data["year"] = get_numbers_from_filename(file)
    df_from_each_file.append(data)

In [19]:
df_from_each_file

[     Land Kreis Gemeinde                             Name1  \
 0      01   001      000           St. Franziskus-Hospital
 1      01   001      000                      Privatklinik
 2      01   001      000            Diakonissenkrankenhaus
 3      01   001      000                      Förde-Klinik
 4      01   002      000                    Lubinus-Klinik
 ...   ...   ...      ...                               ...
 2146   16   076      022             Klinik ProLeben Greiz
 2147   16   076      061        Kreiskrankenhaus Ronneburg
 2148   16   077      001  Kreiskrankenhaus Altenburg gGmbH
 2149   16   077      001       Evangelische Lukas-Stiftung
 2150   16   077      043        Krankenhaus Schmölln gGmbH

                              Name2                   Name3 Name4  \
 0                              NaN                     NaN   NaN
 1                  Dr. Dunckelmann                     NaN   NaN
 2                              NaN                     NaN   NaN
 3                              NaN                     NaN   NaN
 4                              NaN                     NaN   NaN
 ...                            ...                     ...   ...
 2146                           NaN                     NaN   NaN
 2147  Fachklinik für Geriatrie und    Innere Medizin gGmbH   NaN
 2148                           NaN                     NaN   NaN
 2149                     Altenburg  Klinik für Psychiatrie   NaN
 2150                           NaN                     NaN   NaN

                          Straße/Hausnr    PLZ               Ort  \
 0                          Waldstr. 17  24939         Flensburg
 1                  Reepschlägerbahn 34  24937         Flensburg
 2                  Marienhölzungsweg 2  24939         Flensburg
 3                    Mürwiker Str. 115  24943  Flensburg-Mürwik
 4                    Steenbeker Weg 25  24106              Kiel
 ...                                ...    ...               ...
 2146                       Gartenweg 6  07973             Greiz
 2147  Straße d. Opfer d. Faschismus 15  07580         Ronneburg
 2148                  Am Waldessaum 10  04600         Altenburg
 2149                 Zeitzer Straße 28  04600         Altenburg
 2150             Robert-Koch-Straße 95  04626          Schmölln

      Telefonvorwahl/-nummer Telefaxvorwahl/-nummer  \
 0                 0461/8160           0461/8162012
 1               0461/141150           0461/1411520
 2                0461/81201           0461/8121107
 3                0461/31910            0461/311460
 4                 0431/3880            0431/388240
 ...                     ...                    ...
 2146           03661/689870                    NaN
 2147             036602/550                    NaN
 2148              03447/520                    NaN
 2149             03447/5620                    NaN
 2150             034491/300                    NaN

                                        E-Mail Adresse  \
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 ...                                               ...
 2146                           Pro_Leben_Greiz@gmx.de
 2147                    post@Krankenhaus-Ronneburg.de
 2148                        kkh-altenburg@t-online.de
 2149  verwaltungsdirektion@lukasstiftung-altenburg.de
 2150                            KHSchmoellnTh@aol.com

                         Internetadresse Traeger                       T_Name1  \
 0                                   NaN       4  Malteser St. Franziskus GmbH
 1                                   NaN       5          Dr. med. Dunckelmann
 2                                   NaN       4   Ev.-luth.Diakonissenanstalt
 3                                   NaN       5             Silke Feldt-Hamel
 4          http://www.lubinus-klinik.de       5      Dr. med. Hans H. Lubinus
 ...                                 ...     ...                           ...
 2146                    www.proleben.de       5                      ProLeben
 2147                                NaN       3               Landkreis Greiz
 2148  www.kreiskrankenhaus-altenburg.de       3              Kreiskrankenhaus
 2149     www.lukasstiftung-altenburg.de       4   Evangelische Lukas-Stiftung
 2150                                NaN       3    Krankenhaus Schmölln gGmbH

                           T_Name2 T_Name3 T_Name4 Art Betten_Ins Augen  \
 0                             NaN     NaN     NaN   2        324   NaN
 1                             NaN     NaN     NaN   2         20   NaN
 2                             NaN     NaN     NaN   2        504     2
 3                             NaN     NaN     NaN   2         28   NaN
 4                             NaN     NaN     NaN   2        212   NaN
 ...                           ...     ...     ...  ..        ...   ...
 2146  Fachbehandlungszentrum GmbH     NaN     NaN   4         12   NaN
 2147                          NaN     NaN     NaN   2        100   NaN
 2148              Altenburg gGmbH     NaN     NaN   2        496   NaN
 2149                    Altenburg     NaN     NaN   2         60   NaN
 2150                          NaN     NaN     NaN   2        113   NaN

      Chirurgie Ch_Gefäßchir Ch_Thorax Ch_Unfall Ch_Viszeral Frauen/Geburt  \
 0          104          NaN       NaN       NaN         NaN           NaN
 1          NaN          NaN       NaN       NaN         NaN           NaN
 2          102          NaN        52        50         NaN            61
 3          NaN          NaN       NaN       NaN         NaN            28
 4           74            4       NaN       NaN         NaN           NaN
 ...        ...          ...       ...       ...         ...           ...
 2146       NaN          NaN       NaN       NaN         NaN           NaN
 2147       NaN          NaN       NaN       NaN         NaN           NaN
 2148       160           29       NaN        63          68            64
 2149       NaN          NaN       NaN       NaN         NaN           NaN
 2150       NaN          NaN       NaN       NaN         NaN           NaN

      F_Frau F_Geburt  HNO Haut_Geschlecht Herzchir Herz_Thorax Innere I_Angio  \
 0       NaN      NaN    7             NaN      NaN         NaN    162     NaN
 1       NaN      NaN  NaN             NaN      NaN         NaN    NaN     NaN
 2       NaN      NaN   11             NaN      NaN         NaN    129     NaN
 3       NaN      NaN  NaN             NaN      NaN         NaN    NaN     NaN
 4       NaN      NaN  NaN             NaN      NaN         NaN    NaN     NaN
 ...     ...      ...  ...             ...      ...         ...    ...     ...
 2146    NaN      NaN  NaN             NaN      NaN         NaN    NaN     NaN
 2147    NaN      NaN  NaN             NaN      NaN         NaN    100     NaN
 2148     37       27    2             NaN      NaN         NaN    179      80
 2149    NaN      NaN  NaN             NaN      NaN         NaN    NaN     NaN
 2150    NaN      NaN  NaN             NaN      NaN         NaN    113     NaN

      I_Endo I_Gastro I_Haema I_Kardio I_Klin-Geriatrie I_Nephro I_Pneumo  \
 0       NaN      NaN     NaN      NaN               45      NaN      NaN
 1       NaN      NaN     NaN      NaN              NaN      NaN      NaN
 2       NaN      NaN     NaN      NaN              NaN      NaN      NaN
 3       NaN      NaN     NaN      NaN              NaN      NaN      NaN
 4       NaN      NaN     NaN      NaN              NaN      NaN      NaN
 ...     ...      ...     ...      ...              ...      ...      ...
 2146    NaN      NaN     NaN      NaN              NaN      NaN      NaN
 2147    NaN      NaN     NaN      NaN              100      NaN      NaN
 2148    NaN      NaN     NaN      NaN              NaN       99      NaN
 2149    NaN      NaN     NaN      NaN              NaN      NaN      NaN
 2150    NaN      NaN     NaN      NaN              NaN      NaN      NaN

      I_Rheuma Kinderchir Kinderhk K_Kardiologie K_Neonatologie Kinderpsychiat  \
 0         NaN        NaN      NaN           NaN            NaN            NaN
 1         NaN        NaN      NaN           NaN            NaN            NaN
 2         NaN        NaN       49           NaN            NaN            NaN
 3         NaN        NaN      NaN           NaN            NaN            NaN
 4         NaN        NaN      NaN           NaN            NaN            NaN
 ...       ...        ...      ...           ...            ...            ...
 2146      NaN        NaN      NaN           NaN            NaN            NaN
 2147      NaN        NaN      NaN           NaN            NaN            NaN
 2148      NaN         22       34           NaN            NaN            NaN
 2149      NaN        NaN      NaN           NaN            NaN            NaN
 2150      NaN        NaN      NaN           NaN            NaN            NaN

      Mund_Kiefer Neurochir Neurologie Nuklear Ortho O_Rheuma Plast Chir  \
 0              6       NaN        NaN     NaN    42      NaN        NaN
 1            NaN       NaN        NaN     NaN    20      NaN        NaN
 2            NaN        47        NaN     NaN   NaN      NaN         10
 3            NaN       NaN        NaN     NaN   NaN      NaN        NaN
 4            NaN       NaN        NaN     NaN   138      NaN        NaN
 ...          ...       ...        ...     ...   ...      ...        ...
 2146         NaN       NaN        NaN     NaN   NaN      NaN        NaN
 2147         NaN       NaN        NaN     NaN   NaN      NaN        NaN
 2148         NaN       NaN         35     NaN   NaN      NaN        NaN
 2149         NaN       NaN        NaN     NaN   NaN      NaN        NaN
 2150         NaN       NaN        NaN     NaN   NaN      NaN        NaN

      Psychiat Psychotherapeut Strahlen Urologie Sonst TN_Innere  \
 0         NaN             NaN      NaN      NaN     3        20
 1         NaN             NaN      NaN      NaN   NaN       NaN
 2          52             NaN      NaN       41   NaN       NaN
 3         NaN             NaN      NaN      NaN   NaN       NaN
 4         NaN             NaN      NaN      NaN   NaN       NaN
 ...       ...             ...      ...      ...   ...       ...
 2146      NaN             NaN      NaN      NaN    12       NaN
 2147      NaN             NaN      NaN      NaN   NaN       NaN
 2148      NaN             NaN      NaN      NaN   NaN       NaN
 2149       60             NaN      NaN      NaN   NaN       NaN
 2150      NaN             NaN      NaN      NaN   NaN       NaN

      TN_I_Klin-Geriatrie TN_Kinderpsychiat TN_Psychiat TN_Psychotherapeut  \
 0                    NaN               NaN         NaN                NaN
 1                    NaN               NaN         NaN                NaN
 2                    NaN               NaN          33                NaN
 3                    NaN               NaN         NaN                NaN
 4                    NaN               NaN         NaN                NaN
 ...                  ...               ...         ...                ...
 2146                 NaN               NaN         NaN                NaN
 2147                 NaN               NaN         NaN                NaN
 2148                 NaN               NaN         NaN                NaN
 2149                 NaN               NaN          20                NaN
 2150                 NaN               NaN         NaN                NaN

      TN_Sonst TN_SUM  year
 0         NaN     20  2003
 1         NaN    NaN  2003
 2         NaN     33  2003
 3         NaN    NaN  2003
 4         NaN    NaN  2003
 ...       ...    ...   ...
 2146      NaN    NaN  2003
 2147      NaN    NaN  2003
 2148      NaN    NaN  2003
 2149      NaN     20  2003
 2150      NaN    NaN  2003

 [2151 rows x 69 columns],
      Land Kreis Gemeinde                             Name1  \
 0      01   001      000            Diakonissenkrankenhaus
 1      01   001      000           St. Franziskus-Hospital
 2      01   001      000                      Förde-Klinik
 3      01   002      000                    Lubinus-Klinik
 4      01   002      000        Psychiatrische Tagesklinik
 ...   ...   ...      ...                               ...
 2120   16   076      022             Klinik ProLeben Greiz
 2121   16   076      061        Kreiskrankenhaus Ronneburg
 2122   16   077      001  Kreiskrankenhaus Altenburg gGmbH
 2123   16   077      001       Evangelische Lukas-Stiftung
 2124   16   077      043        Krankenhaus Schmölln gGmbH

                              Name2                   Name3 Name4  \
 0                              NaN                     NaN   NaN
 1                              NaN                     NaN   NaN
 2                              NaN                     NaN   NaN
 3                              NaN                     NaN   NaN
 4                 "Kieler Fenster"                     NaN   NaN
 ...                            ...                     ...   ...
 2120                           NaN                     NaN   NaN
 2121  Fachklinik für Geriatrie und    Innere Medizin gGmbH   NaN
 2122                           NaN                     NaN   NaN
 2123                     Altenburg  Klinik für Psychiatrie   NaN
 2124                           NaN                     NaN   NaN

                          Straße/Hausnr    PLZ                Ort  \
 0                           Knuthstr.1  24939          Flensburg
 1                          Waldstr. 17  24939          Flensburg
 2                    Mürwiker Str. 115  24943   Flensburg-Mürwik
 3                    Steenbeker Weg 25  24106               Kiel
 4             Alte Lübecker Chaussee 1  24114               Kiel
 ...                                ...    ...                ...
 2120                       Gartenweg 6  07973              Greiz
 2121  Straße d. Opfer d. Faschismus 15  07580          Ronneburg
 2122                  Am Waldessaum 10  04600          Altenburg
 2123                 Zeitzer Straße 28  04600          Altenburg
 2124             Robert-Koch-Straße 95  04626           Schmölln

      Telefonvorwahl/-nummer Telefaxvorwahl/-nummer  \
 0                0461/81201           0461/8121107
 1                 0461/8160           0461/8162012
 2                0461/31910            0461/311460
 3                 0431/3880            0431/388240
 4              0431/6498020                    NaN
 ...                     ...                    ...
 2120           03661/689870                    NaN
 2121             036602/550           036602/55209
 2122              03447/520                    NaN
 2123             03447/5620           03447/562150
 2124             034491/300           034491/30151

                                        E-Mail Adresse  \
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 ...                                               ...
 2120                           pro_leben_greiz@gmx.de
 2121                    post@krankenhaus-ronneburg.de
 2122                        kkh-altenburg@t-online.de
 2123  verwaltungsdirektion@lukasstiftung-altenburg.de
 2124                            khschmoellnth@aol.com

                         Internetadresse Traeger                       T_Name1  \
 0                                   NaN       4   Ev.-luth.Diakonissenanstalt
 1                                   NaN       4  Malteser St. Franziskus GmbH
 2                                   NaN       5             Silke Feldt-Hamel
 3               www.lubinus-clinikum.de       5      Dr. med. Hans H. Lubinus
 4                                   NaN       4          Verein zur Förderung
 ...                                 ...     ...                           ...
 2120                    www.proleben.de       5                      ProLeben
 2121                                NaN       3               Landkreis Greiz
 2122  www.kreiskrankenhaus-altenburg.de       3              Kreiskrankenhaus
 2123     www.lukasstiftung-altenburg.de       4   Evangelische Lukas-Stiftung
 2124                                NaN       3    Krankenhaus Schmölln gGmbH

                           T_Name2           T_Name3         T_Name4 Art  \
 0                             NaN               NaN             NaN   2
 1                             NaN               NaN             NaN   3
 2                             NaN               NaN             NaN   2
 3                             NaN               NaN             NaN   2
 4             Sozialpädagogischer  Initiativen e.V.  Kieler Fenster   2
 ...                           ...               ...             ...  ..
 2120  Fachbehandlungszentrum GmbH               NaN             NaN   4
 2121                          NaN               NaN             NaN   2
 2122              Altenburg gGmbH               NaN             NaN   2
 2123                    Altenburg               NaN             NaN   2
 2124                          NaN               NaN             NaN   2

      Betten_Ins Augen Chirurgie Ch_Gefäßchir Ch_Thorax Ch_Unfall Ch_Viszeral  \
 0           516     2       102          NaN        52        50         NaN
 1           325   NaN       104          NaN       NaN       NaN         NaN
 2            24   NaN       NaN          NaN       NaN       NaN         NaN
 3           212   NaN        74            4       NaN       NaN         NaN
 4           NaN   NaN       NaN          NaN       NaN       NaN         NaN
 ...         ...   ...       ...          ...       ...       ...         ...
 2120         12   NaN       NaN          NaN       NaN       NaN         NaN
 2121         90   NaN       NaN          NaN       NaN       NaN         NaN
 2122        476   NaN       160           28       NaN        63          69
 2123         60   NaN       NaN          NaN       NaN       NaN         NaN
 2124        113   NaN       NaN          NaN       NaN       NaN         NaN

      Frauen/Geburt F_Frau F_Geburt  HNO Haut_Geschlecht Herzchir Herz_Thorax  \
 0               61    NaN      NaN   11             NaN      NaN         NaN
 1              NaN    NaN      NaN    8             NaN      NaN         NaN
 2               24    NaN      NaN  NaN             NaN      NaN         NaN
 3              NaN    NaN      NaN  NaN             NaN      NaN         NaN
 4              NaN    NaN      NaN  NaN             NaN      NaN         NaN
 ...            ...    ...      ...  ...             ...      ...         ...
 2120           NaN    NaN      NaN  NaN             NaN      NaN         NaN
 2121           NaN    NaN      NaN  NaN             NaN      NaN         NaN
 2122            56     33       23    1             NaN      NaN         NaN
 2123           NaN    NaN      NaN  NaN             NaN      NaN         NaN
 2124           NaN    NaN      NaN  NaN             NaN      NaN         NaN

      Innere I_Angio I_Endo I_Gastro I_Haema I_Kardio I_Klin-Geriatrie  \
 0       129     NaN    NaN      NaN     NaN      NaN              NaN
 1       162     NaN    NaN      NaN     NaN      NaN               45
 2       NaN     NaN    NaN      NaN     NaN      NaN              NaN
 3       NaN     NaN    NaN      NaN     NaN      NaN              NaN
 4       NaN     NaN    NaN      NaN     NaN      NaN              NaN
 ...     ...     ...    ...      ...     ...      ...              ...
 2120    NaN     NaN    NaN      NaN     NaN      NaN              NaN

In [20]:
df_2003_2005 = pd.concat(df_from_each_file, ignore_index=True)

In [21]:
df_2003_2005 = df_2003_2005[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins', 'year']]

In [22]:
df_2003_2005.sample(10)

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,year
3244,08,111,000,Psychotherapeutische Klinik,Stuttgart,4,Sonnenbergklinik gGmbH,2,102,2004
5701,09,173,135,Fachklinik Lenggries,Lenggries,5,Fachklinik Lenggries GmbH,3,20,2005
2768,05,558,032,St. Gerburgis-Hospital,Nottuln,4,Christophorus-Träger-GmbH /,2,110,2004
2362,03,251,012,Kreiskrankenhaus,Diepholz,3,Landkreis Diepholz,2,160,2004
4609,03,459,024,Evangelisches Krankenhaus,Melle,4,Christliches Klinikum,2,248,2005
1365,08,435,016,Psychiatrische Tagesklinik,Friedrichshafen,4,Arkade-Pauline 13 GmbH,2,NaN,2003
2200,01,055,028,August-Bier-Klinik,Malente-Gremsmühlen,2,Stiftung,2,82,2004
4623,04,011,000,Klinikum,Bremen,3,Klinikum,2,899,2005
397,05,113,000,Kath. Kliniken Essen-Nord,Essen,4,Kath. Kliniken Essen-Nord gGmbH,2,546,2003
1703,09,673,114,NESSA-Klinik,Bad Neustadt a.d. Saale,5,NESSA-Klinik,4,8,2003

## 2006

In [68]:
df_2006 = pd.read_excel('KHV_2006.xls', sheet_name=4, dtype='object')
df_2006["year"] = get_numbers_from_filename(file)
df_2006 = df_2006[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins', 'year']]

## 2007 - 2015

In [24]:
filenames =  [
 'KHV_2007.xls',
 'KHV_2008.xls',
 'KHV_2009.xls',
 'KHV_2010.xls',
 'KHV_2011.xls',
 'KHV_2012.xlsx',
 'KHV_2013.xlsx',
 'KHV_2014.xlsx',
 'KHV_2015.xlsx']

In [25]:
## df_from_each_file = (pd.read_excel(file, sheet_name=4, dtype='object') for file in filenames)

df_from_every_file = []

for file in filenames:
    data = pd.read_excel(file, sheet_name=4, skiprows=4, dtype='object')
    data["year"] = get_numbers_from_filename(file)
    df_from_every_file.append(data)

In [26]:
df_2007_2015 = pd.concat(df_from_every_file, ignore_index=True)

In [27]:
df_2007_2015 = df_2007_2015[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins', 'year']]

## Add more columns

In [28]:
def label_art(row):
    if row == 1 :
        return "Uniklinik"
    if row == 2 :
        return "Plankrankenhaus"
    if row == 3 :
        return "mit Versorgungsvertrag"
    if row == 4 :
        return "ohne Versorgungsvertrag"
    if row == 5 :
        return "Bundeswehrkrankenhaus"

In [58]:
def clean_betreiber(x):
    if 'HELIOS' in x:
        return 'HELIOS'
    if 'ASKLEPIOS' in x:
        return 'ASKLEPIOS'
    if 'DRK' in x:
        return 'DRK'
    #TODO Check for other betreiber
    else:
        return x

In [157]:
def check_traeger(x):
    if 1 <= x <= 4:
       return "oeffentlich"
    elif x == 5:
       return "privat"
    else:
       return "keine Angabe"

In [158]:
def add_more_columns(df):
    df.Traeger = df.Traeger.fillna(0)
    df.Traeger = df.Traeger.astype('int')
    df["private_traeger"]= df.Traeger.apply(check_traeger)
    # np.where(cond1, exp1, np.where(cond2, exp2, ...))
    # df.Traeger.apply(lambda x: "oeffentlich" if 1 <= x <= 4 elif x == 5 "privat" else "keine Angabe")

    df["art_text"]= df.Art.apply(lambda x: label_art(x))
    df["betreiber"] = df.T_Name1.str.strip().str.upper()
    df.betreiber = df.betreiber.astype('str', errors='ignore')
    df.betreiber = df.betreiber.apply(clean_betreiber)
    df.Betten_Ins = df.Betten_Ins.astype('int', errors='ignore')
    return df

In [155]:
df_1992 = add_more_columns(df_1992)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [138]:
df_1995 = add_more_columns(df_1995)

In [139]:
df_2003_2005 = add_more_columns(df_2003_2005)
#Todo Convert floats to int?

In [140]:
df_2003_2005.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,year,art_text,betreiber,private_traeger
3089,06,611,000,Klinikum,Kassel,2,Klinikum,2,1093,2004,None,KLINIKUM,oeffentlich

In [141]:
df_2006 = add_more_columns(df_2006)

In [142]:
df_2006.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,year,art_text,betreiber,private_traeger
2054,16,075,085,Thüringen-Klinik Pößneck gGmbH,Pößneck,3,Thüringen-Kliniken,2,112,2015,None,THÜRINGEN-KLINIKEN,oeffentlich

In [143]:
df_2007_2015 = add_more_columns(df_2007_2015)

TypeError: '<=' not supported between instances of 'str' and 'int'

In [106]:
df_2007_2015.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,year,art_text,betreiber
2521,05,358,008,St. Marien-Hospital,Düren,4,Caritas Trägergesellschaft West,2,364,2008,None,CARITAS TRÄGERGESELLSCHAFT WEST

## Bring them all together

In [71]:
dfs = [df_1992, df_1995, df_2003_2005, df_2006, df_2007_2015]

In [72]:
df = pd.concat(dfs, ignore_index=True)

In [74]:
df.to_pickle("Krankenhäuser.pkl")