In [7]:
import pandas as pd
import os

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 1862)

## 1992

In [8]:
df_1992 = pd.read_excel('KHV_1992.xls', dtype='object')

In [9]:
df_1992.sample()

,LAND,REGBEZ,KREIS,GEMEINDE,NAME1,NAME2,NAME3,NAME4,STRASSE,PLZ,ORT,TELEFON,TRAEGER,NAMET1,NAMET2,NAMET3,NAMET4,ART,BETTEN_P,BETTEN_I,AUGEN_P,AUGEN_I,CHIR_P,CHIR_I,C_GEF_P,C_GEF_I,C_KIN_P,C_KIN_I,C_PLA_P,C_PLA_I,C_THOR_P,C_THOR_I,C_UNF_P,C_UNF_I,FRAUEN_P,FRAUEN_I,F_FRAU_P,F_FRAU_I,F_GEBURT,F_GEBUR0,HNO_P,HNO_I,HUG_P,HUG_I,INNERE_P,INNERE_I,I_ENDO_P,I_ENDO_I,I_GAST_P,I_GAST_I,I_HAEM_P,I_HAEM_I,I_KARD_P,I_KARD_I,I_LUB_P,I_LUB_I,I_NEPH_P,I_NEPH_I,I_RHEUM_,I_RHEUM1,I_GER_P,I_GER_I,KINDER_P,KINDER_I,KJPSYCH_,KJPSYCH2,MKG_P,MKG_I,NEURCH_P,NEURCH_I,NEUROL_P,NEUROL_I,NUKLEAR_,NUKLEAR3,ORTH_P,ORTH_I,O_RHEU_P,O_RHEU_I,PSYCH_P,PSYCH_I,P_SUCHT_,P_SUCHT4,PSYSOM_P,PSYSOM_I,STRAHL_P,STRAHL_I,UROL_P,UROL_I,SONST_P,SONST_I,TN_GER,TN_KJPSY,TN_PSYCH,TN_PSYSO,TN_SONST,TN_SUM
1085,07,1,37,226,Neurologische Klinik,NaN,NaN,NaN,Heerstraáe 54/65/67,56179,Vallendar,(0261)-64050,2,Bund Deutscher,Hirnbesch„digter e.V.,NaN,NaN,2,64,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [10]:
df_1992.columns

Index(['LAND', 'REGBEZ', 'KREIS', 'GEMEINDE', 'NAME1', 'NAME2', 'NAME3',
       'NAME4', 'STRASSE', 'PLZ', 'ORT', 'TELEFON', 'TRAEGER', 'NAMET1',
       'NAMET2', 'NAMET3', 'NAMET4', 'ART', 'BETTEN_P', 'BETTEN_I', 'AUGEN_P',
       'AUGEN_I', 'CHIR_P', 'CHIR_I', 'C_GEF_P', 'C_GEF_I', 'C_KIN_P',
       'C_KIN_I', 'C_PLA_P', 'C_PLA_I', 'C_THOR_P', 'C_THOR_I', 'C_UNF_P',
       'C_UNF_I', 'FRAUEN_P', 'FRAUEN_I', 'F_FRAU_P', 'F_FRAU_I', 'F_GEBURT',
       'F_GEBUR0', 'HNO_P', 'HNO_I', 'HUG_P', 'HUG_I', 'INNERE_P', 'INNERE_I',
       'I_ENDO_P', 'I_ENDO_I', 'I_GAST_P', 'I_GAST_I', 'I_HAEM_P', 'I_HAEM_I',
       'I_KARD_P', 'I_KARD_I', 'I_LUB_P', 'I_LUB_I', 'I_NEPH_P', 'I_NEPH_I',
       'I_RHEUM_', 'I_RHEUM1', 'I_GER_P', 'I_GER_I', 'KINDER_P', 'KINDER_I',
       'KJPSYCH_', 'KJPSYCH2', 'MKG_P', 'MKG_I', 'NEURCH_P', 'NEURCH_I',
       'NEUROL_P', 'NEUROL_I', 'NUKLEAR_', 'NUKLEAR3', 'ORTH_P', 'ORTH_I',
       'O_RHEU_P', 'O_RHEU_I', 'PSYCH_P', 'PSYCH_I', 'P_SUCHT_', 'P_SUCHT4',
       'PSYSOM_P', 'PSYSOM_I', 'STRAHL_P', 'STRAHL_I', 'UROL_P', 'UROL_I',
       'SONST_P', 'SONST_I', 'TN_GER', 'TN_KJPSY', 'TN_PSYCH', 'TN_PSYSO',
       'TN_SONST', 'TN_SUM'],
      dtype='object')

In [11]:
# TODO: Prüfen: Steht BETTEN_I für Betten insgesamt?
df_1992 = df_1992.rename(columns={'LAND': 'Land', 'KREIS': 'Kreis', 'GEMEINDE': 'Gemeinde', 'NAME1': 'Name1', 'ORT': 'Ort', 'TRAEGER': 'Traeger', 'NAMET1': 'T_Name1', 'ART':'Art', 'BETTEN_I': 'Betten_Ins'})

In [12]:
df_1992 = df_1992[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

## 1995

In [13]:
df_1995 = pd.read_excel('KHV_1995.XLS', 'KH', dtype='object')

In [14]:
# TODO: Prüfen: Steht BETTEN_I für Betten insgesamt?
df_1995 = df_1995.rename(columns={'LAND': 'Land', 'KREIS': 'Kreis', 'GEMEINDE': 'Gemeinde', 'NAME1': 'Name1', 'ORT': 'Ort', 'TRAEGER': 'Traeger', 'NAMET1': 'T_Name1', 'ART':'Art', 'BETTEN_I': 'Betten_Ins'})

In [15]:
df_1995 = df_1995[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

In [16]:
df_1995.dtypes

Land          object
Kreis         object
Gemeinde      object
Name1         object
Ort           object
Traeger       object
T_Name1       object
Art           object
Betten_Ins    object
dtype: object

In [17]:
df_1995 = df_1995[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

## 2003 - 2005

In [18]:
filenames = [
 'KHV_2003.xls',
 'KHV_2004.xls',
 'KHV_2005.xls',]

In [19]:
df_from_each_file = (pd.read_excel(file, 'KHV', dtype='object') for file in filenames)
df_2003_2005 = pd.concat(df_from_each_file, ignore_index=True)

In [20]:
df_2003_2005 = df_2003_2005[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

## 2006 - 2015

In [21]:
filenames =  [
 'KHV_2006.xls',
 'KHV_2007.xls',
 'KHV_2008.xls',
 'KHV_2009.xls',
 'KHV_2010.xls',
 'KHV_2011.xls',
 'KHV_2012.xlsx',
 'KHV_2013.xlsx',
 'KHV_2014.xlsx',
 'KHV_2015.xlsx']

In [24]:
df_from_each_file = (pd.read_excel(file, sheet_name=4, dtype='object') for file in filenames)
df_2006_2015 = pd.concat(df_from_each_file, ignore_index=True)

In [25]:
df_2006_2015 = df_2003_2005[['Land', 'Kreis', 'Gemeinde', 'Name1', 'Ort', 'Traeger', 'T_Name1', 'Art', 'Betten_Ins']]

## Add more columns

In [26]:
def label_art(row):
    if row == 1 :
        return "Uniklinik"
    if row == 2 :
        return "Plankrankenhaus"
    if row == 3 :
        return "mit Versorgungsvertrag"
    if row == 4 :
        return "ohne Versorgungsvertrag"
    if row == 5 :
        return "Bundeswehrkrankenhaus"

In [27]:
def clean_betreiber(x):
    if 'HELIOS' in x:
        return 'HELIOS'
    #TODO Check for other betreiber
    else:
        return x

In [28]:
def add_more_columns(df):
    df.Traeger = df.Traeger.astype('int')
    df["private_traeger"]= df.Traeger.apply(lambda x: "oeffentlich" if x <= 4 else "privat")
    df["art_text"]= df.Art.apply(lambda x: label_art(x))
    df["betreiber"] = df.T_Name1.str.strip().str.upper()
    df.betreiber = df.betreiber.astype('str')
    df.betreiber = df.betreiber.apply(clean_betreiber)
    df.Betten_Ins = df.Betten_Ins.astype('int', errors='ignore')
    return df

In [29]:
df_1992 = add_more_columns(df_1992)

In [30]:
df_1995 = add_more_columns(df_1995)

In [134]:
df_2003_2005 = add_more_columns(df_2003_2005)
#Todo Convert floats to int?

/home/p3nny/2_wdr-data/ddj-krankenhaus/myvenv/lib/python3.6/site-packages/pandas/core/generic.py:5159: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
/home/p3nny/2_wdr-data/ddj-krankenhaus/myvenv/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/p3nny/2_wdr-data/ddj-krankenhaus/myvenv/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/p3nny/2_wdr-data/ddj-krankenhaus/myvenv/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [31]:
df_2003_2005.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins
238,03,351,006,Allgemeines Krankenhaus,Celle,4,Allgemeines Krankenhaus Celle,2,661

In [32]:
df_2006_2015 = add_more_columns(df_2006_2015)

In [33]:
df_2006_2015.sample()

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,private_traeger,art_text,betreiber
6053,11,002,002,Augenklinik im Ringcenter,Berlin,5,Dr. Pahlitzsch,4,4,privat,None,DR. PAHLITZSCH

## Bring them all together

In [34]:
dfs = [df_1992, df_1995, df_2003_2005, df_2006_2015]

In [35]:
df = pd.concat(dfs, ignore_index=True)

In [36]:
df

,Land,Kreis,Gemeinde,Name1,Ort,Traeger,T_Name1,Art,Betten_Ins,private_traeger,art_text,betreiber
0,01,01,000,Privatklinik Dr. Dunckelmann,Flensburg,3,Dr. med. Dunckelmann,2,20,oeffentlich,Plankrankenhaus,DR. MED. DUNCKELMANN
1,01,01,000,Evangelisch-lutherische,Flensburg,2,Evangelisch-lutherische,2,395,oeffentlich,Plankrankenhaus,EVANGELISCH-LUTHERISCHE
2,01,01,000,Psychiatrische Tagesklinik,Flensburg,2,Evangelisch-lutherische,2,0,oeffentlich,Plankrankenhaus,EVANGELISCH-LUTHERISCHE
3,01,01,000,St. Franziskus-Hospital,Flensburg,2,Genossenschaft der,2,337,oeffentlich,Plankrankenhaus,GENOSSENSCHAFT DER
4,01,01,000,St„dtische Krankenanstalten,Flensburg,1,Stadt Flensburg,2,140,oeffentlich,Plankrankenhaus,STADT FLENSBURG
...,...,...,...,...,...,...,...,...,...,...,...,...
17380,16,076,022,Klinik ProLeben Greiz,Greiz,5,ProLeben,4,12,privat,None,PROLEBEN
17381,16,076,022,Kreiskrankenhaus Greiz GmbH,Greiz,3,Landkreis Greiz,2,321,oeffentlich,None,LANDKREIS GREIZ
17382,16,076,061,Kreiskrankenhaus Ronneburg,Ronneburg,3,Landkreis Greiz,2,93,oeffentlich,None,LANDKREIS GREIZ
17383,16,077,001,Evangelische Lukas-Stiftung,Altenburg,4,Evangelische Lukas-Stiftung,2,60,oeffentlich,None,EVANGELISCHE LUKAS-STIFTUNG
17384,16,077,001,Kreiskrankenhaus Altenburg gGmbH,Altenburg,3,Kreiskrankenhaus,2,567,oeffentlich,None,KREISKRANKENHAUS